### ISSUE TITLE
Start minimized

### ISSUE THREAD

**Issue by Endogen** [miho/SonoAir#4]
Most of the time i just start the app and do not need to do anything else with it, so i minimize it and that's it. Would be helpfull if you could implement a "start minimized" option.

**Comment by tiberiumihai** [comment]
I tried to set SonoAir to run on startup and check the box to start hidden.
![sonosair-statup-minimized](https://cloud.githubusercontent.com/assets/12754525/9613146/5979c90c-50f2-11e5-9cd0-aa68d42da389.png)

Apparently, on next startup, SonoAir window shows up blank. I thought it would have started it hidden/minimized in the background. This is what happens:
![sonosair-startup-minimized-issue](https://cloud.githubusercontent.com/assets/12754525/9613150/61c16976-50f2-11e5-8879-2fec791afd7e.png)

BTW Thanks for your work Miho!

**Comment by tiberiumihai** [comment]
Guys if you want to start SonoAir hidden at startup you can create an Automator script just like this one:
![sonos-startup-minimized-using-automator-](https://cloud.githubusercontent.com/assets/12754525/9623961/c50d1b16-5150-11e5-8abb-fc859ea1899a.png)

And then add it at startup in SystemPreferences > User Groups > Login Items.
![sonos-startup-script](https://cloud.githubusercontent.com/assets/12754525/9618187/63f5ddd8-510d-11e5-9018-24d49b280416.png)

**Comment by Endogen** [comment]
Thanks, that's helpful but still, i don't want to use it all the time. For me, it's better to start the app if i need it (not on startup) and then close it again if i don't.
So it would still be awesome to have a "start minimized" option.

**Comment by miho** [comment]
The newest version ([1.0 Beta 6](http://sonoair.mihosoft.eu/)) can start minimized (see preferences).
