### ISSUE TITLE
iOS 9 Public Beta

### ISSUE THREAD

**Issue by messerram** [miho/SonoAir#7]
iOS 9 public Beta don't see any Speakers from SonoAir. But my Raspberry Pi with airSonos also fails, no Speakers shown up on iOS9 Public beta.

**Comment by miho** [comment]
Related to: stephen/nodetunes/issues/1 Unfortunately, I didn't have the opportunity to update to iOS 9 yet since my only iOS device is used in a production environment where updating is currently not possible.

**Comment by miho** [comment]
Works with [1.0 Beta 6](http://sonoair.mihosoft.eu/).
